### ISSUE TITLE
Sync members to mailchimp

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#120]
- [ ] Subscription creation: https://n8n.commonknowledge.coop/workflow/17
- [ ] Subscription deletion = cancel

**Comment by janbaykara** [comment]
@melaniepatrick are there any **automated** membership ladder emails that go out, starting with a "thanks for joining!" kind of thing? If so, how do they work?

**Comment by melaniepatrick** [comment]
Yes.
Good question.
I think there is one that is automated that Fergus created to go out when
people sign up. But I've never been able to access it or change it. I only
know about it because people have forwarded it on to me when asking about
their subscription. I think he automated it with Mailgun maybe? I gave him
some text for it but we never worked on it together. I've never been able
to find it in Stripe.

Because I had no control over that and I wasn't clear if people always
received it, I also have an auto welcome email in Mailchimp. This goes out
to them the day after they sign up. It includes their discount codes etc.
So it's not a receipt, it's more of a welcome email. It is sent out to
anyone who is added to the mailing list with the tag 'member' but I can
obviously edit this one, or we can change the settings.

Like I said before we should also be asking people's permission to email
them from Mailchimp.

I think getting an automated email receipt for signing up is a good idea
though.

Stripe has settings for choosing whether to email people receipts. I have
decided against doing it, because I don't want people to get a reminder
each month that they are paying out, as the amounts are generally small.
This is however more of an issue if someone is paying annually. I would
like to give them a receipt for that. I used to login to Stripe and send
all annual subscribers a receipt manually. But I have stopped doing that
now as I just couldn't find time for it.

**Comment by janbaykara** [comment]
Thanks, that's really helpful info.

And from memory you said that members are currently arriving into Mailchimp via manual import? Or is there also an automated sync between the website and the Mailchimp?

**Comment by janbaykara** [comment]
OK, so I'm going to take this as the mailchimp sync task. In general, when a stripe subscription changes, we want Mailchimp to mirror their subscription product and status.

Because needs might change over time, my thinking is that we should connect stripe and zapier together using an automation platform like [Zapier](zapier.com/) or [n8n](https://n8n.io/), rather than with bespoke code that only a developer can change.

I personally think n8n is a great fit for this stuff because of its simple pricing plan and flexible powerful features (and is open source, could be self hosted!), but Zapier is maybe a bit more familiar or user friendly, if a bit more expensive.

- [n8n cloud page](https://www.n8n.cloud/) (for pricing, scroll down)
- [Zapier pricing page](https://zapier.com/pricing)

If we went this direction, we'd set up the automation platform and then sit down together to look at how to configure some workflows.

What do you think about this, @melaniepatrick?
