### ISSUE TITLE
Account signup shouldn't forget your `next` url, even if there are validation errors

### ISSUE THREAD

**Issue by janbaykara** [commonknowledge/leftbookclub#228]

**Comment by janbaykara** [comment]
First reported in #215

**Comment by janbaykara** [comment]
@melaniepatrick FYI that the recent signup issue, which took users to the homepage after user entered an invalid password, has now been fixed, and these signups will continue the user on to checkout after signup.

**Comment by melaniepatrick** [comment]
Thanks for fixing that. I will write and let them know they can now login again and add their payment info.

One thing: I'm looking at the checkout process again and I can see you have changed the text on the buttons. I preferred what we had before! Can you let me know what you thinking is here? Asking them to do two things on each button ('Save and register' and then'Register and checkout') is unclear and sounds more onerous I think? So I'd prefer to go back to 'Continue' and 'Sign up' unless there was a specific problem with that?

Also: I don't want them to have to tick a terms and conditions box. I think by signing up to become a member they are automatically agreeing to this. If it's necessary to state that somewhere then we can think about where to put it? Asking for their permission to email them is crucial, but the T&Cs and privacy policy are already there for all to see if they want to check them out.

Always feel free to give me a call if you want to talk through these changes, I know you are trying to minimize time spent but I think it's better just to agree them first. Thanks!

**Comment by melaniepatrick** [comment]
Hi Jan, I just ran a test on this and the problem is still happening -- it just sent me to the home page when I made a mistake with my password? Then when I go into my account and press 'Become a Member' it does it again?

**Comment by janbaykara** [comment]
Hi @melaniepatrick.

I hear you on the button labelling. This happened whilst I was setting up separate buttons for logged out and logged in users, but maybe the execution got a bit muddled. Thoughts in my head at the time.
  - I wanted to make it clear for logged in users that the next page would be Stripe Checkout
  - I was worried that people might get puzzled about the steps involved in signing up so wanted to be super explicit about what comes next after going through the form, which we know from research is generally appreciated
  
How about this, then:
  - Checkout page: `continue` or `sign up` (logged out) / `checkout` (logged in)
  - Registration page: `continue to checkout` or simply `checkout`

I'm unable to replicate this redirect issue and puzzled because mechanically this isn't how it works now, could we jump on a very quick call to look at this? I am meant to be off work today but can quickly call in about this issue as it might affect payments.

Perhaps let's send "become a member" link clickers to the /join page?

**Comment by melaniepatrick** [comment]
Thanks Jan. I'm sorry I haven't got back to you before now. Happy to have a call on Monday if you still want to.
From what you say, I think you have already sorted the button issue. Looking good now. I always think the less text, the better. So 'Continue' 'Checkout' both v good.

Redirect issue: Yes definitely let's send them to the Join page when they click 'Become a Member'

I should specify that my journey was via Login (rather than Join) as that is what I had seen a few people do online. As we mentioned on the other thread. So this is why the journey was account first/pick sub after. Hopefully fewer people will now do this, as we have made 'Join' more obvious. But because I deliberately made an error with the password, it still directed me back to the homepage. Perhaps I am confusing things. I will run some more tests this weekend and try and work out if there is some remaining issue.

And ok on the terms and conditions. Ideally I think I'd rather have small text 'By continuing with this purchase you agree to the T&C and privacy policy as displayed on our website'. But I'm happy to stick with the tick box if you are very sure it's not affecting conversions. It's not a massive priority and I don't want to take up unnecessary time!

**Comment by janbaykara** [comment]
Right, I see why you've ended up that way!

When you sign up outside of the checkout flow (i.e. by clicking log in, then clicking "join") then there is no checkout flow to continue to, so you will be redirected to the homepage. That's by design. However what I've now done is linked "Not a member? Join" to the `/join` page so that your signup will happen once you enter the checkout flow. Hope that makes sense.

Let's meet on Monday regardless for a weekly check in, say 11am? Or else you could pick a time from my diary: https://janbaykara.youcanbook.me/

**Comment by melaniepatrick** [comment]
Thanks Jan. Yes 11 is good, let's do that. Speak to you later.
Shall we do zoom again?
